---
name: CI

on: push

jobs:
  assure-unique-container:
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/heads/')
    name: assure unique »ubi-minimal« container in repository
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Check constraint
        run: |
          test 1 -eq $(grep --only-matching --no-filename 'ubi-minimal:[0-9][0-9.-]*' -R . | uniq | wc -l)

  test-and-build:
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/heads/')
    strategy:
      matrix:
        go: [ '1.22', '1.23', '1.24' ]
    container: registry.access.redhat.com/ubi8/ubi-minimal:8.10-1179
    name: Test and Build w/ Go v${{ matrix.go }}
    needs: assure-unique-container
    steps:
      - name: Install prerequisites
        run: microdnf install tar gzip findutils gcc make

      - uses: actions/checkout@v4
        name: Checkout code

      - uses: actions/setup-go@v5
        name: Install Go v${{ matrix.go }}
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Download/Install IBM MQ Redistributable
        run: |
          # https://developer.ibm.com/articles/mq-downloads/
          mkdir /opt/mqm
          curl -L https://ibm.biz/IBM-MQC-Redist-LinuxX64targz | tar xzf - -C /opt/mqm/

      - name: Build
        run: |
          make
